import Header from '../components/Header'
import './globals.css'
import { Inter } from 'next/font/google'
import Footer from '../components/Footer'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Technology Ecommerce',
  description: 'Generated by create next app',
}

export default function RootLayout({  children,}: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='dark:bg-cyan-950'>
          <Header/>  
        
            {children}
    
          <Footer />
        </div>
        
      </body>
    </html>
  )
}